// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Water_Pump_Tanzania
{
    public partial class PumpMaintenanceModel
    {
        /// <summary>
        /// model input class for PumpMaintenanceModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"id")]
            public float Id { get; set; }

            [ColumnName(@"amount_tsh")]
            public float Amount_tsh { get; set; }

            [ColumnName(@"date_recorded")]
            public DateTime Date_recorded { get; set; }

            [ColumnName(@"funder")]
            public string Funder { get; set; }

            [ColumnName(@"gps_height")]
            public float Gps_height { get; set; }

            [ColumnName(@"installer")]
            public string Installer { get; set; }

            [ColumnName(@"longitude")]
            public float Longitude { get; set; }

            [ColumnName(@"latitude")]
            public float Latitude { get; set; }

            [ColumnName(@"wpt_name")]
            public string Wpt_name { get; set; }

            [ColumnName(@"num_private")]
            public float Num_private { get; set; }

            [ColumnName(@"basin")]
            public string Basin { get; set; }

            [ColumnName(@"subvillage")]
            public string Subvillage { get; set; }

            [ColumnName(@"region")]
            public string Region { get; set; }

            [ColumnName(@"region_code")]
            public float Region_code { get; set; }

            [ColumnName(@"district_code")]
            public float District_code { get; set; }

            [ColumnName(@"lga")]
            public string Lga { get; set; }

            [ColumnName(@"ward")]
            public string Ward { get; set; }

            [ColumnName(@"population")]
            public float Population { get; set; }

            [ColumnName(@"public_meeting")]
            public bool Public_meeting { get; set; }

            [ColumnName(@"recorded_by")]
            public string Recorded_by { get; set; }

            [ColumnName(@"scheme_management")]
            public string Scheme_management { get; set; }

            [ColumnName(@"scheme_name")]
            public string Scheme_name { get; set; }

            [ColumnName(@"permit")]
            public bool Permit { get; set; }

            [ColumnName(@"construction_year")]
            public float Construction_year { get; set; }

            [ColumnName(@"extraction_type")]
            public string Extraction_type { get; set; }

            [ColumnName(@"extraction_type_group")]
            public string Extraction_type_group { get; set; }

            [ColumnName(@"extraction_type_class")]
            public string Extraction_type_class { get; set; }

            [ColumnName(@"management")]
            public string Management { get; set; }

            [ColumnName(@"management_group")]
            public string Management_group { get; set; }

            [ColumnName(@"payment")]
            public string Payment { get; set; }

            [ColumnName(@"payment_type")]
            public string Payment_type { get; set; }

            [ColumnName(@"water_quality")]
            public string Water_quality { get; set; }

            [ColumnName(@"quality_group")]
            public string Quality_group { get; set; }

            [ColumnName(@"quantity")]
            public string Quantity { get; set; }

            [ColumnName(@"quantity_group")]
            public string Quantity_group { get; set; }

            [ColumnName(@"source")]
            public string Source { get; set; }

            [ColumnName(@"source_type")]
            public string Source_type { get; set; }

            [ColumnName(@"source_class")]
            public string Source_class { get; set; }

            [ColumnName(@"waterpoint_type")]
            public string Waterpoint_type { get; set; }

            [ColumnName(@"waterpoint_type_group")]
            public string Waterpoint_type_group { get; set; }

            [ColumnName(@"status_group")]
            public string Status_group { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PumpMaintenanceModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"id")]
            public float Id { get; set; }

            [ColumnName(@"amount_tsh")]
            public float Amount_tsh { get; set; }

            [ColumnName(@"date_recorded")]
            public DateTime Date_recorded { get; set; }

            [ColumnName(@"funder")]
            public string Funder { get; set; }

            [ColumnName(@"gps_height")]
            public float Gps_height { get; set; }

            [ColumnName(@"installer")]
            public string Installer { get; set; }

            [ColumnName(@"longitude")]
            public float Longitude { get; set; }

            [ColumnName(@"latitude")]
            public float Latitude { get; set; }

            [ColumnName(@"wpt_name")]
            public string Wpt_name { get; set; }

            [ColumnName(@"num_private")]
            public float Num_private { get; set; }

            [ColumnName(@"basin")]
            public float[] Basin { get; set; }

            [ColumnName(@"subvillage")]
            public string Subvillage { get; set; }

            [ColumnName(@"region")]
            public string Region { get; set; }

            [ColumnName(@"region_code")]
            public float Region_code { get; set; }

            [ColumnName(@"district_code")]
            public float District_code { get; set; }

            [ColumnName(@"lga")]
            public string Lga { get; set; }

            [ColumnName(@"ward")]
            public string Ward { get; set; }

            [ColumnName(@"population")]
            public float Population { get; set; }

            [ColumnName(@"public_meeting")]
            public float Public_meeting { get; set; }

            [ColumnName(@"recorded_by")]
            public string Recorded_by { get; set; }

            [ColumnName(@"scheme_management")]
            public string Scheme_management { get; set; }

            [ColumnName(@"scheme_name")]
            public string Scheme_name { get; set; }

            [ColumnName(@"permit")]
            public float Permit { get; set; }

            [ColumnName(@"construction_year")]
            public float Construction_year { get; set; }

            [ColumnName(@"extraction_type")]
            public string Extraction_type { get; set; }

            [ColumnName(@"extraction_type_group")]
            public string Extraction_type_group { get; set; }

            [ColumnName(@"extraction_type_class")]
            public float[] Extraction_type_class { get; set; }

            [ColumnName(@"management")]
            public float[] Management { get; set; }

            [ColumnName(@"management_group")]
            public string Management_group { get; set; }

            [ColumnName(@"payment")]
            public string Payment { get; set; }

            [ColumnName(@"payment_type")]
            public string Payment_type { get; set; }

            [ColumnName(@"water_quality")]
            public float[] Water_quality { get; set; }

            [ColumnName(@"quality_group")]
            public string Quality_group { get; set; }

            [ColumnName(@"quantity")]
            public string Quantity { get; set; }

            [ColumnName(@"quantity_group")]
            public float[] Quantity_group { get; set; }

            [ColumnName(@"source")]
            public string Source { get; set; }

            [ColumnName(@"source_type")]
            public float[] Source_type { get; set; }

            [ColumnName(@"source_class")]
            public string Source_class { get; set; }

            [ColumnName(@"waterpoint_type")]
            public string Waterpoint_type { get; set; }

            [ColumnName(@"waterpoint_type_group")]
            public float[] Waterpoint_type_group { get; set; }

            [ColumnName(@"status_group")]
            public uint Status_group { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PumpMaintenanceModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
